inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - example/**/*.rb

Style/TrivialAccessors:
  Exclude:
    - lib/prawn/label_sheet/configuration.rb
Style/Documentation:
  Exclude:
    - lib/prawn/label_sheet/configuration.rb
